name: Python package

on:
  push:
    branches: [ master, lab3 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working_dir: app_python
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f ${{ env.working_dir }}/requirements.txt ]; then pip install -r ${{ env.working_dir }}/requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest ${{ env.working_dir }}/test.py
